# Generated by Django 4.0.5 on 2022-09-03 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import phonenumber_field.modelfields
import user.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('event_venue', models.CharField(max_length=200)),
                ('event_logo', models.ImageField(default='avatar.jpg', upload_to='profile_images')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=30, null=True)),
                ('pin', models.CharField(max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('category', models.CharField(blank=True, choices=[('STANDARD PASS', 'STANDARD PASS'), ('GOLD PASS', 'GOLD PASS'), ('PLATINUM PASS', 'PLATINUM PASS')], default=None, max_length=100, null=True)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.event')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=20, null=True)),
                ('othernames', models.CharField(max_length=40, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('image', models.ImageField(default='avatar.jpg', upload_to='profile_images')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_drink', multiselectfield.db.fields.MultiSelectField(choices=[('More Beer', 'More Beer'), ('Bottle Water', 'Bottle Water'), ('Malt', 'Malt'), ('Heineken', 'Heineken'), ('Trophy lager', 'Trophy lager'), ('Hero', 'Hero'), ('Goldberg', 'Goldberg'), ('Gulder', 'Gulder'), ('STAR Lager Beer', 'STAR Lager Beer'), ('33 Export Lager Beer', '33 Export Lager Beer'), ('Tiger Lager Beer', 'Tiger Lager Beer'), ('Life Lager Beer', 'Life Lager Beer')], max_length=255)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('value', models.CharField(blank=True, default=user.models.generate_pin, max_length=6)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='Not Activated', max_length=30)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.ticket')),
            ],
            options={
                'unique_together': {('ticket', 'value')},
            },
        ),
    ]
