# Generated by Django 4.0.5 on 2022-06-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_date', models.DateField(auto_now_add=True)),
                ('event_venue', models.CharField(max_length=200)),
                ('event_ticket', models.CharField(max_length=100)),
                ('login_logo', models.ImageField(default='avatar.jpg', upload_to='profile_images')),
                ('desktop_logo', models.ImageField(default='avatar.jpg', upload_to='profile_images')),
                ('mobile_logo', models.ImageField(default='avatar.jpg', upload_to='profile_images')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
