# Generated by Django 4.0.5 on 2022-06-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('RECHARGE PIN', 'RECHARGE PIN'), ('DIRECT PAYMENT', 'DIRECT PAYMENT')], default=None, max_length=100)),
                ('status', models.BooleanField()),
                ('added_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
