# Generated by Django 4.0.5 on 2022-06-16 07:26

from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, default=user.models.generate_pin, max_length=6)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.ticket')),
            ],
            options={
                'unique_together': {('ticket', 'value')},
            },
        ),
    ]
