# Generated by Django 4.0.5 on 2022-06-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('ACTIVATED', 'ACTIVATED'), ('NOT ACTIVATED', 'NOT ACTIVATED')], default=None, max_length=100),
        ),
    ]
