# Generated by Django 4.0.5 on 2022-06-18 07:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
