# Generated by Django 4.0.5 on 2022-06-18 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_pin_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.ticket'),
        ),
    ]
