# Generated by Django 4.0.5 on 2022-06-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_event_event_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_ticket',
            field=models.CharField(max_length=100),
        ),
    ]
