# Generated by Django 4.0.5 on 2022-06-18 09:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_ticket_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='id',
        ),
        migrations.AddField(
            model_name='pin',
            name='reference',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
