# Generated by Django 4.0.5 on 2022-06-18 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_pin_id_pin_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='name',
            new_name='event',
        ),
    ]
