# Generated by Django 4.0.5 on 2022-06-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_rename_name_ticket_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_ticket',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(),
        ),
    ]
