# Generated by Django 4.0.5 on 2022-06-18 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_event_event_ticket_alter_event_event_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='desktop_logo',
            new_name='event_logo',
        ),
        migrations.RemoveField(
            model_name='event',
            name='login_logo',
        ),
        migrations.RemoveField(
            model_name='event',
            name='mobile_logo',
        ),
    ]
