# Generated by Django 4.0.5 on 2022-06-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_pin_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='reference',
            field=models.UUIDField(default='e279c5', editable=False, primary_key=True, serialize=False),
        ),
    ]
