# Generated by Django 4.0.5 on 2022-06-18 20:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_pin_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='reference',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
