# Generated by Django 4.0.5 on 2022-06-23 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='cashier',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
    ]
