# Generated by Django 4.0.5 on 2022-06-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_rename_cashier_profile_user_remove_profile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='status',
        ),
        migrations.AddField(
            model_name='pin',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
