# Generated by Django 4.0.5 on 2022-06-25 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_pin_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='staff',
        ),
    ]
