# Generated by Django 4.0.5 on 2022-06-27 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_rename_user_profile_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='staff',
            new_name='user',
        ),
    ]
