# Generated by Django 4.0.5 on 2022-06-29 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_pin_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='user',
        ),
        migrations.AlterField(
            model_name='pin',
            name='status',
            field=models.CharField(default='Not Activated', max_length=30),
        ),
    ]
