# Generated by Django 4.0.5 on 2022-07-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='guest_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
