# Generated by Django 4.0.5 on 2022-07-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_choices_drink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choices',
            name='description',
        ),
        migrations.AddField(
            model_name='choices',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
