# Generated by Django 4.0.5 on 2022-07-04 23:43

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_remove_drink_user_drink_drink_title_delete_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='title',
        ),
        migrations.AddField(
            model_name='drink',
            name='guest_drinke',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('More Beer', 'More Beer'), ('Bottle Water', 'Bottle Water'), ('Malk', 'Malk'), ('Coke', 'Coke'), ('Wine', 'Wine')], default=2, max_length=37),
            preserve_default=False,
        ),
    ]
