# Generated by Django 4.0.5 on 2022-07-04 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_remove_drink_title_drink_guest_drinke'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='guest_drinke',
            new_name='guest_drink',
        ),
    ]
