# Generated by Django 4.0.5 on 2022-07-08 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_rename_guest_drinke_drink_guest_drink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='ticket',
        ),
        migrations.AddField(
            model_name='guest',
            name='pin',
            field=models.OneToOneField(max_length=6, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.pin'),
        ),
    ]
