# Generated by Django 4.0.5 on 2022-07-08 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_alter_guest_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='pin',
            field=models.OneToOneField(max_length=6, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.pin'),
        ),
    ]
