# Generated by Django 4.0.5 on 2022-07-08 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_alter_guest_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='pin',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
