# Generated by Django 4.0.5 on 2022-07-15 18:42

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_alter_guest_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='guest_drink',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('More Beer', 'More Beer'), ('Bottle Water', 'Bottle Water'), ('Malt', 'Malt'), ('Heineken', 'Heineken'), ('Trophy lager', 'Trophy lager'), ('Hero', 'Hero'), ('Goldberg', 'Goldberg'), ('Gulder', 'Gulder'), ('STAR Lager Beer', 'STAR Lager Beer'), ('33 Export Lager Beer', '33 Export Lager Beer'), ('Tiger Lager Beer', 'Tiger Lager Beer'), ('Life Lager Beer', 'Life Lager Beer')], max_length=255),
        ),
    ]
