# Generated by Django 4.0.5 on 2022-07-15 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_alter_drink_guest_drink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.event'),
        ),
    ]
