# Generated by Django 4.0.5 on 2022-07-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0041_alter_pin_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='category',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('STANDARD PASS', 'STANDARD PASS'), ('GOLD PASS', 'GOLD PASS'), ('PLATINUM PASS', 'PLATINUM PASS')], default=None, max_length=100),
        ),
    ]
