# Generated by Django 4.0.5 on 2022-07-16 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0042_remove_ticket_category_ticket_ticket_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_type',
            new_name='category',
        ),
    ]
